[package]
name = "evote-crypto-rs"
version = "0.1.0"
authors = ["Alexander Hofmann <alexhofmann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies.wasm-bindgen]
version = "0.2"