# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  setup:
    description: "Setup cargo"
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y pkg-config
      - run: cargo --version
      - run: |
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
          cargo install wasm-pack

  rustfmt:
    description: "Check formatting"
    steps:
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    description: "Lint"
    steps:
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings

  build:
    description: "Build"
    steps:
      - run: cargo +nightly build --verbose --release --target wasm32-unknown-unknown

  build_wasm:
    description: "Build WASM-js bindings"
    steps:
      - run: wasm-pack build

  store_cache:
    description: "Save cache"
    steps:
      - save_cache:
          key: cargo-{{checksum "Cargo.lock"}}
          paths:
            - "~/.cargo"

jobs:
  build:
    docker:
      - image: cimg/rust:1.46.0
        environment:
          - CARGO_TERM_COLOR: always
    steps:
      - checkout
      - setup
      - restore_cache:
          keys:
            - cargo-{{checksum "Cargo.lock"}}
      - build
      - build_wasm
      - store_cache
  test:
    docker:
      - image: cimg/rust:1.46.0
        environment:
          - CARGO_TERM_COLOR: always
    steps:
      - checkout
      - run: cargo install cargo2junit
      - run: |
          mkdir -p ~/test-results/
          cargo test --verbose --all-features -- -Z unstable-options --format json | tee ~/test-results/results.json
      - run:
          name: Save test results
          command: cat ~/test-results/results.json | cargo2junit > ~/test-results/results.xml
          when: always
      - store_test_results:
          path: ~/test-results

  format-and-lint:
    docker:
      - image: cimg/rust:1.46.0
        environment:
          - CARGO_TERM_COLOR: always
    steps:
      - checkout
      - rustfmt
      - clippy


# Orchestrate or schedule a set of jobs
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - format-and-lint:
          requires:
            - build
      
